export const SET_ROOT_VALUE = 'SET_ROOT_VALUE';

export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';

export const PUT_PROFILE = 'PUT_PROFILE';
export const PUT_PROFILE_SUCCESS = 'PUT_PROFILE_SUCCESS';
export const PUT_PROFILE_FAILURE = 'PUT_PROFILE_FAILURE';

export const LOGOUT = 'LOGOUT';
